package org.firstinspires.ftc.teamcode.util;

public enum Direction {
    STRAIGHT_FORWARD, STRAIGHT_BACKWARD,
    SLIDE_LEFT, SLIDE_RIGHT,
    ROTATE_LEFT, ROTATE_RIGHT,
    TURN_LEFT_FORWARDS, TURN_RIGHT_FORWARDS,
    TURN_LEFT_BACKWARDS, TURN_RIGHT_BACKWARDS,
    DIAGONALLY_RIGHT_FORWARD, DIAGONALLY_RIGHT_BACKWARD,
    DIAGONALLY_LEFT_FORWARD, DIAGONALLY_LEFT_BACKWARD
}
