package org.firstinspires.ftc.teamcode.util;

public enum Direction {
    STRAIGHT_FORWARD, STRAIGHT_BACKWARD, STRAIGHT_LEFT, STRAIGHT_RIGHT,
    DIAGONALLY_RIGHT_FORWARDS, DIAGONALLY_LEFT_FORWARDS, DIAGONALLY_RIGHT_BACKWARDS, DIAGONALLY_LEFT_BACKWARDS,
    STEER_LEFT, STEER_RIGHT
}
